#!/bin/sh

# PROVIDE: transmissionvpn
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="transmissionvpn"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

transmissionvpn_start()
{
    service transmission onestop
    /opt/transmissionvpn/start_vpn.sh
}

transmissionvpn_stop()
{
    service transmission onestop
    #/opt/transmissionvpn/stop_vpn.sh
}


load_rc_config $name
run_rc_command "$1"
